# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_manager', '0003_auto_20181019_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='target_num',
            new_name='finished',
        ),
        migrations.AddField(
            model_name='tag',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
