# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_manager', '0004_auto_20181020_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='level',
            new_name='department_level',
        ),
        migrations.AddField(
            model_name='department',
            name='department_desc',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Mô Tả'),
        ),
    ]
