# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 18:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simplemde.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kpi_manager', '0005_auto_20181025_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_leader',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='leader_title',
            field=models.CharField(default='Trưởng Phòng', max_length=225),
        ),
        migrations.AddField(
            model_name='department',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_desc',
            field=simplemde.fields.SimpleMDEField(blank=True, null=True),
        ),
    ]
