# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 18:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kpi_manager', '0007_auto_20181025_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, default='Nhân Viên', max_length=225, null=True)),
                ('removed', models.BooleanField(default=False, verbose_name='Loại Bỏ')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kpi_manager.Department', verbose_name='Phòng Ban')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Thành Viên')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
    ]
