# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_manager', '0010_auto_20181025_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmember',
            name='department_member',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kpi_manager.Profile'),
        ),
    ]
