# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import simplemde.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_manager', '0014_auto_20181025_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='period_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời Gian Kết Thúc'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='period_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời Gian Bắt Đầu'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='state',
            field=models.CharField(blank=True, choices=[('NF', 'Chưa Hoàn Thành'), ('PR', 'Đang Thực Hiện'), ('CO', 'Hoàn Thành')], max_length=2, null=True, verbose_name='Trạng Thái'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_description',
            field=simplemde.fields.SimpleMDEField(blank=True, null=True, verbose_name='Mô Tả'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Công Việc'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kpi_manager.Profile', verbose_name='Nhân Viên'),
        ),
    ]
