# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 20:35
from __future__ import unicode_literals

from django.db import migrations
import simplemde.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_manager', '0017_auto_20181025_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=simplemde.fields.SimpleMDEField(blank=True, null=True),
        ),
    ]
