# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_manager', '0018_auto_20181025_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department_leader',
        ),
        migrations.RemoveField(
            model_name='department',
            name='leader_title',
        ),
        migrations.AddField(
            model_name='departmentmember',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
    ]
