# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_manager', '0025_auto_20181029_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_description_safe',
            field=models.TextField(blank=True, null=True, verbose_name='Mô Tả'),
        ),
    ]
