# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_manager', '0026_tag_tag_description_safe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_description_safe',
            field=models.TextField(blank=True, null=True, verbose_name='Mô Tả (HTML)'),
        ),
    ]
