# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_manager', '0028_remove_tag_tag_description_safe'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='period_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời Gian Kết Thúc'),
        ),
        migrations.AddField(
            model_name='task',
            name='period_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời Gian Bắt Đầu'),
        ),
    ]
