# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_manager', '0031_auto_20181112_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='progress',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
