# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-23 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_manager', '0032_auto_20181117_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktime',
            name='time_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
