# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-24 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_manager', '0034_remove_worktime_rest_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktime',
            name='rest_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
